import { useEffect, useState } from "react";
import api from "../api/axios";
import toast from "react-hot-toast";

export default function DoctorDashboard() {
  const [appointments, setAppointments] = useState([]);
  const [openSummaryId, setOpenSummaryId] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const token = localStorage.getItem("doctorToken");

        const res = await api.get("/appointments/doctor", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        setAppointments(res.data);
      } catch (err) {
        console.error("Failed to fetch appointments", err);
      }
    };

    fetchData();
  }, []);

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-3xl font-bold">Doctor Dashboard</h2>

        <a
          href="/doctor/add-clinic"
          className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
        >
          + Add Clinic
        </a>
      </div>

      {/* Appointments */}
      <div className="space-y-6">
        {appointments.map((a) => (
          <div
            key={a._id}
            className="bg-white rounded-xl shadow-md p-6"
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <p>
                <span className="font-semibold">Patient:</span>{" "}
                {a.patient?.name}
              </p>

              <p>
                <span className="font-semibold">Clinic:</span>{" "}
                {a.clinic?.name}
              </p>

              <p>
                <span className="font-semibold">Slot:</span>{" "}
                {new Date(a.slotTime).toLocaleString("en-IN", {
                  dateStyle: "medium",
                  timeStyle: "short",
                })}
              </p>
            </div>

            <div className="mt-4">
              <p className="font-semibold mb-1">Symptoms</p>
              <div className="bg-gray-50 p-3 rounded-md text-sm text-gray-700">
                {a.symptoms || "No symptoms provided"}
              </div>
            </div>

            {/* AI Summary */}
            {a.aiSummary && (
              <div className="mt-4">
                <button
                  onClick={() =>
                    setOpenSummaryId(
                      openSummaryId === a._id ? null : a._id
                    )
                  }
                  className="text-blue-600 font-medium hover:underline"
                >
                  {openSummaryId === a._id
                    ? "Hide AI Summary"
                    : "View AI Summary"}
                </button>

                {openSummaryId === a._id && (
                  <div className="mt-3 bg-blue-50 border border-blue-100 p-4 rounded-lg">
                    <h4 className="font-semibold mb-2">
                      AI Summary
                    </h4>
                    <p className="text-sm text-gray-700">
                      {a.aiSummary}
                    </p>

                    {a.aiMeta?.source && (
                      <p className="text-xs text-gray-500 mt-2">
                        Generated by{" "}
                        {a.aiMeta.source.toUpperCase()}
                      </p>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* PDF */}
            {a.medicalPdf && (
              <div className="mt-4">
                <button
                  onClick={async () => {
                    try {
                      const token =
                        localStorage.getItem("doctorToken");

                      const res = await api.get(
                        `/appointments/${a._id}/pdf`,
                        {
                          responseType: "blob",
                          headers: {
                            Authorization: `Bearer ${token}`,
                          },
                        }
                      );

                      const url =
                        window.URL.createObjectURL(
                          new Blob([res.data])
                        );

                      const link =
                        document.createElement("a");
                      link.href = url;

                      const safeName =
                        a.patient?.name
                          ?.toLowerCase()
                          .replace(/[^a-z0-9]/gi, "_") ||
                        "patient";

                      link.setAttribute(
                        "download",
                        `medical-record-${safeName}.pdf`
                      );

                      document.body.appendChild(link);
                      link.click();
                      link.remove();

                      toast.success(
                        "PDF downloaded successfully"
                      );
                    } catch (err) {
                      toast.error("Failed to download PDF");
                    }
                  }}
                  className="mt-2 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition"
                >
                  Download Medical PDF
                </button>
              </div>
            )}
          </div>
        ))}

        {appointments.length === 0 && (
          <p className="text-center text-gray-500">
            No appointments found
          </p>
        )}
      </div>
    </div>
  );
}
