import { useEffect, useState } from "react";
import api from "../api/axios";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";

export default function DoctorDashboard() {
  const [appointments, setAppointments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [openSummaryId, setOpenSummaryId] = useState(null);

  const navigate = useNavigate();

  useEffect(() => {
    const fetchAppointments = async () => {
      try {
        const token = localStorage.getItem("doctorToken");

        const res = await api.get("/appointments/doctor", {
          headers: {
            Authorization: `Bearer ${token}`
          }
        });

        setAppointments(res.data);
      } catch (err) {
        toast.error("Failed to load appointments");
      } finally {
        setLoading(false);
      }
    };

    fetchAppointments();
  }, []);

  /* ---------------- LOADING STATE ---------------- */
  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-100">
        <div className="h-12 w-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
        <p className="text-gray-600">
          Loading appointments...
        </p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      {/* HEADER */}
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold">
          Doctor Dashboard
        </h2>

        <button
          onClick={() => navigate("/doctor/add-clinic")}
          className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
        >
          + Add Clinic
        </button>
      </div>

      {/* EMPTY STATE */}
      {appointments.length === 0 && (
        <div className="bg-white rounded-xl p-8 text-center shadow">
          <p className="text-gray-600 mb-2">
            No appointments yet
          </p>
          <p className="text-sm text-gray-500">
            Patients will appear here once they book
          </p>
        </div>
      )}

      {/* APPOINTMENTS */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {appointments.map((a) => (
          <div
            key={a._id}
            className="bg-white rounded-2xl shadow p-6"
          >
            <p className="font-semibold mb-1">
              Patient:{" "}
              <span className="font-normal">
                {a.patient?.name}
              </span>
            </p>

            <p className="text-sm text-gray-600 mb-1">
              Clinic: {a.clinic?.name}
            </p>

            <p className="text-sm text-gray-600 mb-3">
              Slot:{" "}
              {new Date(a.slotTime).toLocaleString(
                "en-IN",
                {
                  dateStyle: "medium",
                  timeStyle: "short"
                }
              )}
            </p>

            <p className="text-sm mb-3">
              <b>Symptoms:</b> {a.symptoms}
            </p>

            {/* AI SUMMARY */}
            {a.aiSummary && (
              <div className="mb-4">
                <button
                  onClick={() =>
                    setOpenSummaryId(
                      openSummaryId === a._id
                        ? null
                        : a._id
                    )
                  }
                  className="text-purple-600 text-sm hover:underline"
                >
                  {openSummaryId === a._id
                    ? "Hide AI Summary"
                    : "View AI Summary"}
                </button>

                {openSummaryId === a._id && (
                  <div className="mt-2 bg-purple-50 border border-purple-200 p-3 rounded-lg">
                    <p className="text-sm">
                      {a.aiSummary}
                    </p>
                    {a.aiMeta?.source && (
                      <p className="text-xs text-gray-500 mt-1">
                        Generated by{" "}
                        {a.aiMeta.source.toUpperCase()}
                      </p>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* PDF DOWNLOAD */}
            {a.medicalPdf && (
              <button
                onClick={async () => {
                  try {
                    const token =
                      localStorage.getItem(
                        "doctorToken"
                      );

                    const res = await api.get(
                      `/appointments/${a._id}/pdf`,
                      {
                        responseType: "blob",
                        headers: {
                          Authorization: `Bearer ${token}`
                        }
                      }
                    );

                    const url =
                      window.URL.createObjectURL(
                        new Blob([res.data])
                      );

                    const link =
                      document.createElement("a");
                    link.href = url;
                    link.setAttribute(
                      "download",
                      "medical-record.pdf"
                    );
                    document.body.appendChild(link);
                    link.click();
                    link.remove();

                    toast.success(
                      "PDF downloaded"
                    );
                  } catch {
                    toast.error(
                      "Failed to download PDF"
                    );
                  }
                }}
                className="mt-3 text-blue-600 text-sm hover:underline"
              >
                Download Medical PDF
              </button>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
